### ISSUE TITLE
Add to dashboard : more UX options

### ISSUE THREAD

**Issue by regel** [regel/chronograf#12]
On the Loud ML page, there is a "Create prediction dashboard" option that always creates a new dashboard.

We can rename "Create prediction dashboard" as "New dashboard"
And also display a 2 level list to users, where they can select the dashboard in which they'd like to insert the new call.

eg 2 level menu:

New dashboard
Add to dashboard >    my dashboard 1
                                    my dashboard 2
                                    my dashboard 3

Or 3 level menu, with a View option to navigate to the relevant dashboard immediately (saves 1 clic):

View in dashboard
New dashboard
Add to dashboard >    my dashboard 1
                                    my dashboard 2
                                    my dashboard 3

**Comment by sbettevy** [comment]
I suggest to split list items to an only one list in a scroller view (saves 1 more click).

View in dashboard
New dashboard
----------------- (= separator item)
-dashboard icon- my dashboard 1
-dashboard icon- my dashboard 2
-dashboard icon- my dashboard 3
-dashboard icon- my dashboard 4

UI/UX aspects are
*small mouse movements/actions to access quick links (View/New) and 'Add to'
*small design (one list / no submenu)
*dashboard icon to denote existing dashboard (= add to)

**Comment by sbettevy** [comment]
![capture d ecran 2018-10-02 a 13 30 32](https://user-images.githubusercontent.com/16062976/46346164-6f795380-c647-11e8-9a8a-9d7838eff2c1.png)

@regel please check or fix correct behavior
Basic options
- [x] `View` is displayed only if dashboard exists (same name as model name)
- [x] `View` action redirect to the correct dashboard
- [x] `New` is displayed only if dashboard does not exist (same naming rule as View)
- [x] `New` action create dashboard and cell
- [x] `New` action does not redirect to the created dashboard

`Add to...` option
- [x] `Add to..` action add or update cell in the selected dashboard
- [x] `Add to...` action does not redirect to the selected dashboard

**Comment by regel** [comment]
Thank you Sam! I'm 100% ok with the UX proposed in your last comment.
