### ISSUE TITLE
Add to annotations, and edit annotations not selectable

### ISSUE THREAD

**Issue by regel** [regel/chronograf#13]
v1.6.1

New "Error" cells added to a dashboard by Loud ML do not allow users to select "Add annotation" or "Edit annotations" although there are indeed annotations displayed in the cell.

I cannot reproduce this issue with standard "Line Graph" cells.

Is the new "Error" cell type missing a property?

**Comment by sbettevy** [comment]
Yes. Property is set on cellSupportsAnnotations function
