### ISSUE TITLE
Error cell pictogram and options

### ISSUE THREAD

**Issue by regel** [regel/chronograf#14]
v1.6.1

The Error cell configuration tab:

- [ ] Is missing its own pictogram
- [ ] Is missing settings that the user can override

**Comment by regel** [comment]
@sbettevy : Can we make this cell generic, without dependencies on Loud ML, and therefore use it in other contexts?
@russorat : Help and advice much appreciated

**Comment by regel** [comment]
1.6.1 panel:

<img width="1251" alt="settings" src="https://user-images.githubusercontent.com/355557/46143293-cbb03200-c259-11e8-8dc1-b2404987abf1.png">

**Comment by sbettevy** [comment]
Sure We can make this cell generic and use it in other contexts. There is no dependencies to Loud ML.

We have to define what specific options to display (right panel) and create a SVG picto.

One option could be `Error` or `Custom` error bar type. `Error` option requires to compute lower and upper values from mid value. This is the standard mode. `Custom` option (what we use for Loud ML) assumes that lower and upper values are already computed (lower = mid - lower error value). This kind of option is available on dygraph options.

**Comment by sbettevy** [comment]
pictogram
![capture d ecran 2018-10-14 a 13 52 49](https://user-images.githubusercontent.com/16062976/46916272-92e1be00-cfb8-11e8-84f0-23920ef7e5e1.png)

**Comment by regel** [comment]
Very nice!

Thinking about the subtitle, there is no "bar" so maybe "Error Graph" will be more accurate?
