### ISSUE TITLE
UI/UX on Anomalies threshold values

### ISSUE THREAD

**Issue by sbettevy** [regel/chronograf#22]
Threshold default values will be set to 0.

It mean that threshold values are automatically computed on the training step.
But these values can be set by hand in the Anomalies panel.

So user see a numeric input field with 0 for auto.
We need to add tooltip to explain how works Loud ML engine and/or create a new component like `FillFeature` to enhance UX.

New component proposal
- show an input field coupled with dropdown choice `number` or `auto`
- when `number` is selected the input field become a number input field with min value of 1 and max value of 100
- when `auto` is selected the input field disappear (0 value for Loud ML)

**Comment by regel** [comment]
Hi @sbettevy do you think we could display 'auto' (instead or 0) directly inside the digital input widget, to avoid the additional drop down? What's the best choice?

**Comment by sbettevy** [comment]
use input for text and number values increase validation complexity. Both types number (int or float) or text have native browser display/format support. So using only one input (text to handle both formats) force us to convert and validate user input (eg '64.a')

IMHO adding new component is the best UX.

Best effort (1 min): add a text to guide users (see screenshot)
![capture d ecran 2018-10-10 a 13 27 33](https://user-images.githubusercontent.com/16062976/46733350-58aeae80-cc90-11e8-833b-18cc258ec6b1.png)

**Comment by regel** [comment]
Alternative: with our smartphones, we are used to simple On|Off sliders that we slide to the right or to the left. Do you think it works to have:

- [ ] Annotations: [Off | On]
- [ ] Auto thresholds: [Off | On], and therefore only show the min/max input when it's needed (Auto threshold = Off).

?

**Comment by sbettevy** [comment]
like this ? (from dashboard visualization panel)
![capture d ecran 2018-10-17 a 18 03 56](https://user-images.githubusercontent.com/16062976/47100192-40fa9b80-d237-11e8-8565-3982d54a03cd.png)

**Comment by regel** [comment]
Yes, so good!

**Comment by sbettevy** [comment]
what are the min/max values?
min=0.1 (because 0 means 'auto')
max? 99.9

**Comment by regel** [comment]
min=0.1
max=100.0

**Comment by sbettevy** [comment]
i have this
![capture d ecran 2018-10-18 a 14 04 13](https://user-images.githubusercontent.com/16062976/47153063-bb322b00-d2de-11e8-9962-adaa8236c4c9.png)

Q: which screen sizes should we support?
- [ ] mobile
- [ ] tablet
- [ ] desktop

**Comment by sbettevy** [comment]
![capture d ecran 2018-10-22 a 09 54 44](https://user-images.githubusercontent.com/16062976/47282711-8f65bc80-d5e0-11e8-97f5-967c6c76a717.png)
